export const servicePages = [
  {
    slug: "knife-sharpening-miami",
    title: "Knife Sharpening Miami | Miami Knife Guy",
    description: "Professional knife sharpening in Miami for Japanese and Western knives, home kitchens, chefs, restaurants, and hospitality teams.",
    eyebrow: "Professional Edge Care · Miami",
    headline: "Knife Sharpening Miami",
    accent: "cyan",
    intro: "Precision sharpening that restores clean geometry, confident cutting, and the glide a well-tuned knife should have.",
    highlights: [
      "Japanese and Western kitchen knives sharpened to the geometry the blade requires.",
      "Chips, rolled edges, damaged tips, and worn profiles evaluated before sharpening.",
      "Service for serious home cooks, chefs, restaurants, hotels, and hospitality teams.",
    ],
    detailTitle: "Built Around the Blade",
    detail: "There is no universal edge angle or one-machine process here. Steel, geometry, use, and condition determine the work. The goal is a sharp, durable edge without unnecessary material removal.",
    faq: [
      { question: "Do you offer knife sharpening in Miami?", answer: "Yes. Miami Knife Guy is based in North Miami Beach and provides professional knife sharpening for clients across Miami-Dade and Broward." },
      { question: "What kinds of knives do you sharpen?", answer: "MKG sharpens Japanese and Western chef knives, utility and paring knives, slicers, serrated knives, steak knives, and many specialty blades." },
      { question: "Do you offer pickup and drop-off?", answer: "Yes. Residential sharpening is completed at the MKG shop. Pickup and return are free within 10 miles for orders of 10 or more knives; otherwise travel is $1 per mile driven. The exact fee and timing are confirmed before scheduling." },
      { question: "Is same-day knife sharpening available?", answer: "Same-day and quick-turnaround shop service may be available depending on the schedule. Rush requests are priced according to current workload and the turnaround requested." },
      { question: "How do I know if my knife needs repair instead of sharpening?", answer: "Chips, broken tips, heavy rust, bends, or a worn profile may require repair before the final edge is sharpened. Photos may be requested to review the condition first." },
      { question: "Do you sharpen serrated knives?", answer: "Yes, when the serration pattern and blade condition make sharpening appropriate. Each serrated knife is reviewed individually." },
      { question: "How do I book knife sharpening?", answer: "Use the Book Service page to choose the service path that fits your kitchen. For damaged or unusual knives, send photos before scheduling." },
    ],
  },
  {
    slug: "restaurant-knife-sharpening-miami",
    title: "Restaurant Knife Sharpening Miami | Sharp After Dark",
    description: "Recurring restaurant knife sharpening in Miami with after-hours collection, fleet tracking, repair, and zero kitchen downtime.",
    eyebrow: "Restaurants · Hotels · Commercial Kitchens",
    headline: "Restaurant Knife Sharpening Miami",
    accent: "pink",
    intro: "A recurring edge program built around the rhythm of service, with scheduled 8 PM–1 AM pickup and 3 AM–8 AM return windows.",
    highlights: [
      "Confirmed after-hours pickup and return windows designed to avoid kitchen downtime.",
      "Recurring weekly, bi-weekly, or monthly programs sized to your knife fleet and volume.",
      "Fleet tracking, chip repair, tip correction, and profile restoration in the same cycle.",
    ],
    detailTitle: "Sharp After Dark",
    detail: "The program is designed for kitchens that cannot afford dull knives or missing tools during prep. Every cycle is planned around operational timing and the way each team actually uses its fleet.",
    bookingPath: "/book/restaurant/",
    faq: [
      { question: "Do you sharpen knives for restaurants in Miami?", answer: "Yes. MKG serves restaurants, hotels, and commercial kitchens across Miami-Dade and Broward with professional fleet sharpening and repair." },
      { question: "Can service be scheduled outside prep or service hours?", answer: "Yes. Sharp After Dark offers scheduled pickup between 8 PM and 1 AM and return between 3 AM and 8 AM. The final appointment is confirmed around the kitchen's preferred timing, location, and MKG route availability." },
      { question: "How far does commercial service travel?", answer: "Commercial service is available throughout Miami-Dade and Broward by scheduled appointment. Timing depends on the kitchen location and the existing service route; immediate on-call service is not offered." },
      { question: "Do you handle recurring restaurant knife programs?", answer: "Yes. Weekly, bi-weekly, monthly, and other recurring intervals can be arranged based on fleet size, volume, and operational needs." },
      { question: "Can you sharpen steak knives for dining rooms?", answer: "Yes. Straight-edge and serviceable serrated steak knives can be handled in batches or included in a recurring restaurant program." },
      { question: "Do you track knife condition over time?", answer: "Recurring programs can include fleet accountability, condition notes, repair needs, and consistent service intervals." },
      { question: "How do restaurants request service?", answer: "Use the Restaurant Service booking page and share the approximate knife count, schedule, location, and any repair or steak-knife needs." },
    ],
  },
  {
    slug: "japanese-knife-sharpening-miami",
    title: "Japanese Knife Sharpening Miami | Miami Knife Guy",
    description: "Expert Japanese knife sharpening in Miami for premium steels, single bevel knives, Nenox, Masamoto, Misono, and other fine cutlery.",
    eyebrow: "Premium Japanese Steel · Single Bevel · Double Bevel",
    headline: "Japanese Knife Sharpening Miami",
    accent: "cyan",
    intro: "Careful edge work for knives whose geometry, steel, and finish deserve more than a generic sharpening process.",
    highlights: [
      "Single-bevel and double-bevel Japanese knives evaluated individually.",
      "Experience with premium makers including Nenox, Masamoto, Misono, and comparable steels.",
      "Controlled material removal that respects blade geometry and long-term service life.",
    ],
    detailTitle: "Trust Matters",
    detail: "Expensive Japanese knives can be permanently altered by careless grinding. MKG works from the blade’s geometry and intended use, preserving the character of the knife while restoring performance.",
    faq: [
      { question: "Do you sharpen Japanese knives in Miami?", answer: "Yes. MKG provides Japanese knife sharpening in Miami for serious home cooks, chefs, and professional kitchens across Miami-Dade and Broward." },
      { question: "Do Japanese knives need different sharpening than Western knives?", answer: "Often, yes. Steel, bevel design, edge geometry, and intended use determine the sharpening approach rather than a single standard angle." },
      { question: "Do you sharpen single-bevel knives?", answer: "Yes. Single-bevel knives require careful attention to the primary bevel, ura, and the geometry already established in the blade." },
      { question: "Can you repair chips in Japanese knives?", answer: "Many chips can be repaired. The correct approach depends on chip depth, steel, blade height, and how the repair will affect the profile." },
      { question: "Do you preserve the knife’s geometry?", answer: "Yes. The work is planned around controlled steel removal and the blade’s existing geometry, with long-term performance in mind." },
      { question: "Should I send photos before booking?", answer: "Send photos for chips, broken tips, corrosion, bends, or finish-sensitive concerns. The knife can then be reviewed before service is confirmed." },
    ],
  },
  {
    slug: "knife-repair-restoration-miami",
    title: "Knife Repair and Restoration Miami | Miami Knife Guy",
    description: "Knife chip repair, broken tip correction, profile restoration, thinning, cleaning, and edge restoration in Miami and South Florida.",
    eyebrow: "Repair · Restoration · Geometry Correction",
    headline: "Knife Repair & Restoration Miami",
    accent: "pink",
    intro: "Damaged knives are assessed as tools, not just edges. The repair plan balances performance, geometry, appearance, and remaining blade life.",
    highlights: [
      "Chip removal and broken-tip correction with controlled reshaping.",
      "Profile restoration for worn, recurved, or uneven blades.",
      "Thinning and geometry correction when sharpening alone will not restore cutting performance.",
    ],
    detailTitle: "Send Photos First",
    detail: "For significant damage, send clear photos of both blade faces, the edge, tip, and full profile. MKG can then give you a more useful preliminary assessment before service.",
    faq: [
      { question: "Do you repair chipped knives?", answer: "Yes. Chip repair is reviewed according to the depth of the damage, the steel, and the amount of material required to restore a usable edge." },
      { question: "Can you fix broken knife tips?", answer: "Many broken tips can be corrected. The repair depends on how much material is missing and how the new profile will affect the knife’s function." },
      { question: "Can rusted knives be restored?", answer: "Some rust and corrosion can be cleaned or reduced, but the result depends on severity and whether pitting has compromised the blade. Photos help establish realistic expectations." },
      { question: "When is a knife too damaged to repair?", answer: "A knife may not be a practical repair if damage affects structural safety, removes too much blade height, or would cost more than the tool reasonably justifies. MKG confirms that honestly before work." },
      { question: "Do you remove as little steel as possible?", answer: "Yes. Repairs are planned to restore function and geometry while preserving as much usable steel and blade life as practical." },
      { question: "Should I send photos before requesting restoration?", answer: "Yes. Send clear photos of both blade faces, the edge, the tip, and the full profile so the condition can be reviewed before service is confirmed." },
    ],
  },
  {
    slug: "steak-knife-sharpening-miami-restaurants",
    title: "Steak Knife Sharpening for Miami Restaurants | MKG",
    description: "Professional steak knife sharpening and recurring dining-room fleet care for Miami restaurants, steakhouses, hotels, and hospitality groups.",
    eyebrow: "Dining Room Edge Care · Restaurants & Hotels",
    headline: "Steak Knife Sharpening for Miami Restaurants",
    accent: "pink",
    intro: "The guest feels the edge before the first bite. Keep dining-room steak knives consistent, clean-cutting, and worthy of the food they serve.",
    highlights: [
      "Recurring fleet service for straight-edge and serviceable serrated steak knives.",
      "Collection and return coordinated around restaurant operations.",
      "Consistent performance across the fleet, with damaged pieces identified during service.",
    ],
    detailTitle: "Protect the Experience",
    detail: "A dull steak knife drags through food and changes the guest’s perception of the plate. Dining-room fleet care treats the knife as part of the hospitality experience.",
    bookingPath: "/book/restaurant/",
    faq: [
      { question: "Do restaurants need steak knives sharpened?", answer: "Yes. Even durable steak knives lose performance through regular dining-room use, dishwashing, and contact with plates." },
      { question: "Why do steak knives matter to the guest experience?", answer: "The guest feels the knife on the first cut. A clean-cutting, consistent fleet supports the food, the table setting, and the standard of service." },
      { question: "Can you service steak knives in batches?", answer: "Yes. Restaurants, steakhouses, and hotels can submit full dining-room batches for assessment and service." },
      { question: "Do you help maintain dining-room knife consistency?", answer: "Yes. Recurring fleet care helps keep sharpness and cutting feel more consistent across the dining room while identifying damaged pieces." },
      { question: "Is steak-knife service part of Sharp After Dark?", answer: "It can be. Steak-knife fleets may be included in an after-hours restaurant program when the schedule and knife type are confirmed." },
      { question: "How do I request steak-knife service?", answer: "Use the Restaurant Service booking page and include the approximate quantity, knife style, condition, and preferred timing." },
    ],
  },
] as const;
