export const servicePages = [
  {
    slug: "knife-sharpening-miami",
    title: "Knife Sharpening Miami | Miami Knife Guy",
    description: "Professional knife sharpening in Miami for Japanese and Western knives, home kitchens, chefs, restaurants, and hospitality teams.",
    eyebrow: "Professional Edge Care · Miami",
    headline: "Knife Sharpening Miami",
    accent: "cyan",
    intro: "Precision sharpening that restores clean geometry, confident cutting, and the glide a well-tuned knife should have.",
    highlights: [
      "Japanese and Western kitchen knives sharpened to the geometry the blade requires.",
      "Chips, rolled edges, damaged tips, and worn profiles evaluated before sharpening.",
      "Service for serious home cooks, chefs, restaurants, hotels, and hospitality teams.",
    ],
    detailTitle: "Built Around the Blade",
    detail: "There is no universal edge angle or one-machine process here. Steel, geometry, use, and condition determine the work. The goal is a sharp, durable edge without unnecessary material removal.",
    faq: [
      { question: "What kinds of knives do you sharpen?", answer: "MKG sharpens Japanese and Western chef knives, utility and paring knives, slicers, serrated knives, steak knives, and many specialty blades." },
      { question: "Can you repair chips while sharpening?", answer: "Yes. Minor chips and edge damage can often be corrected during service. Larger damage is assessed before work begins." },
      { question: "Where do you provide service?", answer: "Miami Knife Guy is based in North Miami Beach and serves select clients across Miami-Dade and Broward." },
    ],
  },
  {
    slug: "restaurant-knife-sharpening-miami",
    title: "Restaurant Knife Sharpening Miami | Sharp After Dark",
    description: "Recurring restaurant knife sharpening in Miami with after-hours collection, fleet tracking, repair, and zero kitchen downtime.",
    eyebrow: "Restaurants · Hotels · Commercial Kitchens",
    headline: "Restaurant Knife Sharpening Miami",
    accent: "pink",
    intro: "A recurring edge program built around the rhythm of service: collected after close, sharpened and repaired, then returned before prep.",
    highlights: [
      "After-hours collection and return designed to avoid kitchen downtime.",
      "Recurring weekly or bi-weekly programs sized to your knife fleet and volume.",
      "Fleet tracking, chip repair, tip correction, and profile restoration in the same cycle.",
    ],
    detailTitle: "Sharp After Dark",
    detail: "The program is designed for kitchens that cannot afford dull knives or missing tools during prep. Every cycle is planned around operational timing and the way each team actually uses its fleet.",
    bookingPath: "/book/restaurant/",
    faq: [
      { question: "Will our kitchen lose access to its knives?", answer: "The program is scheduled to minimize or eliminate downtime, with collection and return coordinated around service and prep." },
      { question: "Can you manage a large knife fleet?", answer: "Yes. Recurring programs can include inventory accountability, tracking, repair notes, and consistent service intervals." },
      { question: "Do you sharpen steak knives?", answer: "Yes. Dining-room steak knife fleets can be serviced as part of a restaurant program." },
    ],
  },
  {
    slug: "japanese-knife-sharpening-miami",
    title: "Japanese Knife Sharpening Miami | Miami Knife Guy",
    description: "Expert Japanese knife sharpening in Miami for premium steels, single bevel knives, Nenox, Masamoto, Misono, and other fine cutlery.",
    eyebrow: "Premium Japanese Steel · Single Bevel · Double Bevel",
    headline: "Japanese Knife Sharpening Miami",
    accent: "cyan",
    intro: "Careful edge work for knives whose geometry, steel, and finish deserve more than a generic sharpening process.",
    highlights: [
      "Single-bevel and double-bevel Japanese knives evaluated individually.",
      "Experience with premium makers including Nenox, Masamoto, Misono, and comparable steels.",
      "Controlled material removal that respects blade geometry and long-term service life.",
    ],
    detailTitle: "Trust Matters",
    detail: "Expensive Japanese knives can be permanently altered by careless grinding. MKG works from the blade’s geometry and intended use, preserving the character of the knife while restoring performance.",
    faq: [
      { question: "Do you sharpen single-bevel knives?", answer: "Yes. Single-bevel knives require specialized attention to the bevel, ura, and existing geometry." },
      { question: "Will sharpening scratch the blade?", answer: "The work is handled carefully, but each knife is assessed for condition and required correction before service. Discuss finish-sensitive concerns when booking." },
      { question: "Can you repair chipped Japanese steel?", answer: "Many chips can be repaired. The best approach depends on chip depth, blade height, steel, and existing profile." },
    ],
  },
  {
    slug: "knife-repair-restoration-miami",
    title: "Knife Repair and Restoration Miami | Miami Knife Guy",
    description: "Knife chip repair, broken tip correction, profile restoration, thinning, cleaning, and edge restoration in Miami and South Florida.",
    eyebrow: "Repair · Restoration · Geometry Correction",
    headline: "Knife Repair & Restoration Miami",
    accent: "pink",
    intro: "Damaged knives are assessed as tools, not just edges. The repair plan balances performance, geometry, appearance, and remaining blade life.",
    highlights: [
      "Chip removal and broken-tip correction with controlled reshaping.",
      "Profile restoration for worn, recurved, or uneven blades.",
      "Thinning and geometry correction when sharpening alone will not restore cutting performance.",
    ],
    detailTitle: "Send Photos First",
    detail: "For significant damage, send clear photos of both blade faces, the edge, tip, and full profile. MKG can then give you a more useful preliminary assessment before service.",
    faq: [
      { question: "Can every broken tip be repaired?", answer: "Many can, but the repair depends on how much material is missing and how the new profile will affect blade function." },
      { question: "What is thinning?", answer: "Thinning reduces material behind the edge when a knife has become too thick to cut efficiently, even after sharpening." },
      { question: "Should I send photos before booking?", answer: "Yes for substantial chips, broken tips, bent blades, heavy corrosion, or restoration work." },
    ],
  },
  {
    slug: "steak-knife-sharpening-miami-restaurants",
    title: "Steak Knife Sharpening for Miami Restaurants | MKG",
    description: "Professional steak knife sharpening and recurring dining-room fleet care for Miami restaurants, steakhouses, hotels, and hospitality groups.",
    eyebrow: "Dining Room Edge Care · Restaurants & Hotels",
    headline: "Steak Knife Sharpening for Miami Restaurants",
    accent: "pink",
    intro: "The guest feels the edge before the first bite. Keep dining-room steak knives consistent, clean-cutting, and worthy of the food they serve.",
    highlights: [
      "Recurring fleet service for straight-edge and serviceable serrated steak knives.",
      "Collection and return coordinated around restaurant operations.",
      "Consistent performance across the fleet, with damaged pieces identified during service.",
    ],
    detailTitle: "Protect the Experience",
    detail: "A dull steak knife drags through food and changes the guest’s perception of the plate. Dining-room fleet care treats the knife as part of the hospitality experience.",
    bookingPath: "/book/restaurant/",
    faq: [
      { question: "Can serrated steak knives be sharpened?", answer: "Many can. Each pattern and condition is assessed to determine whether sharpening is appropriate." },
      { question: "Do you offer recurring service?", answer: "Yes. Steak knife fleets can be included in a recurring restaurant or hotel edge-care program." },
      { question: "Can you service a full dining-room fleet?", answer: "Yes. Share the approximate quantity, knife style, condition, and preferred service interval when booking." },
    ],
  },
] as const;
